name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  azure_login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant: ${{ secrets.AZURE_TENANT_ID }}
