name: This workflow is to trigger IAC pipeline using Terraform

on:
  push:
    branches:
      - main

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLIENT_ID }}
        creds: ${{ secrets.AZURE_CLIENT_SECRET}}
        creds: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: ${{ secrets.AZURE_TENANT_ID }}
    
    - name: Azure CLI
      uses: azure/CLI@v1
      with:
        #azcliversion: 2.30.0
        inlineScript: |
          az account show
