name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  azure_login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Parse Azure Credentials
      id: parse_credentials
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure-credentials.json
        echo "::set-output name=clientSecret::$(jq -r .clientSecret azure-credentials.json)"
        echo "::set-output name=subscriptionId::$(jq -r .subscriptionId azure-credentials.json)"
        echo "::set-output name=tenantId::$(jq -r .tenantId azure-credentials.json)"
        echo "::set-output name=clientId::$(jq -r .clientId azure-credentials.json)"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientSecret": "${{ steps.parse_credentials.outputs.clientSecret }}",
            "subscriptionId": "${{ steps.parse_credentials.outputs.subscriptionId }}",
            "tenantId": "${{ steps.parse_credentials.outputs.tenantId }}",
            "clientId": "${{ steps.parse_credentials.outputs.clientId }}"
          }
